services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  server:
    depends_on:
      - db
    build: .
    ports:
      - "8081:8080"
      - "9229:9229"
    command: npx nodemon --inspect=0.0.0.0:9229 --signal SIGINT --nolazy index.js
    environment:
      - GCP_PROJECT_ID=$GCP_PROJECT_ID
      - GCP_KEYFILENAME=$GCP_KEYFILENAME
      - GCP_BUCKET_NAME=$GCP_BUCKET_NAME
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - JWT_TOKEN=$JWT_TOKEN